version: '3.7'

services:
  book-store-db:
    container_name: book-store-db
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=only4me
      - POSTGRES_USER=admin
      - POSTGRES_DB=book_store_db
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432

  web-app:
    container_name: web-app
    environment:
      - POSTGRES_HOST=book-store-db
      - POSTGRES_PORT=5432
    image: web-app-image
    build:
      context: .
    depends_on:
      - book-store-db
    ports:
      - 8080:8080
